export const GET_ALL_CUSTOMER = 'GET_ALL_CUSTOMER';
export const GET_BY_ID_CUSTOMER = 'GET_BY_ID_CUSTOMER';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';

export const ACTIONS_LIST_CUSTOMER = {
    GET_ALL_CUSTOMER,
    GET_BY_ID_CUSTOMER,
    ADD_CUSTOMER,
    DELETE_CUSTOMER,
    UPDATE_CUSTOMER,
};
