export const GET_ALL_APPOINTMENT = 'GET_ALL_APPOINTMENT';
export const GET_BY_ID_APPOINTMENT = 'GET_BY_ID_APPOINTMENT';
export const ADD_APPOINTMENT = 'ADD_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';

export const ACTIONS_LIST_APPOINTMENT = {
    GET_ALL_APPOINTMENT,
    GET_BY_ID_APPOINTMENT,
    ADD_APPOINTMENT,
    DELETE_APPOINTMENT,
    UPDATE_APPOINTMENT,
};
