export const GET_ALL_EMPLOYEE = 'GET_ALL_EMPLOYEE';
export const GET_BY_ID_EMPLOYEE = 'GET_BY_ID_EMPLOYEE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';

export const ACTIONS_LIST_EMPLOYEE = {
    GET_ALL_EMPLOYEE,
    GET_BY_ID_EMPLOYEE,
    ADD_EMPLOYEE,
    DELETE_EMPLOYEE,
    UPDATE_EMPLOYEE,
};
