export const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS';
export const GET_BY_ID_DEPARTMENTS = 'GET_BY_ID_DEPARTMENTS';
export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';
export const DELETE_DEPARTMENTS = 'DELETE_DEPARTMENTS';
export const UPDATE_DEPARTMENTS = 'UPDATE_DEPARTMENTS';

export const ACTIONS_LIST_DEPARTMENTS = {
    GET_ALL_DEPARTMENTS,
    GET_BY_ID_DEPARTMENTS,
    ADD_DEPARTMENTS,
    DELETE_DEPARTMENTS,
    UPDATE_DEPARTMENTS,
};
